// Este archivo tiene el contenido de las normas jurídicas que se incluyen en la Sección de Fundamentos de Tipo de Documento Petición.

let fundamentos_Peticion = "Toda persona tiene derecho a presentar peticiones respetuosas ante las entidades públicas y privadas en Colombia (Constitución Política de 1991, artículo 23. Ley 1755 de 2015, Colombia).<br/>";
let fundamentos_Habeas_Data = "Toda persona tiene derecho a conocer, actualizar y rectificar las informaciones que se hayan recogido sobre ella en bases de datos o archivos (Ley 1581 de 2012, Colombia).<br/>";
let fundamentos_Informacion_Publica = "Toda persona tiene derecho a solicitar y recibir información y/o documentación pública de cualquier entidad (Ley 1714 de 2012, Colombia).</br>";
let fundamentos_Vida = "Toda persona tiene derecho a que su vida sea protegida por el Estado (Constitución Política de 1991, artículo 11).<br/>";
let fundamentos_Proteccion_Desaparicion_Tortura = "Nadie debe ser sometido a desaparición forzada, a torturas ni a tratos o penas crueles, inhumanos o degradantes (Constitución Política de 1991, artículo 12).<br/>";
let fundamentos_Igualdad = "Todas las personas nacen libres e iguales ante la ley, y deben recibir la misma protección y trato de las autoridades y gozar de los mismos derechos, libertades y oportunidades sin ninguna discriminación por razones de sexo, raza, origen nacional o familiar, lengua, religión, opinión política o filosófica (Constitución Política de 1991, artículo 13).<br/>";
let fundamentos_Personalidad_Juridica = "Toda persona tiene derecho al reconocimiento de su personalidad jurídica (Constitución Política de 1991, artículo 14).<br/>";
let fundamentos_Intimidad_BuenNombre = "Todas las personas tienen derecho a su intimidad personal y familiar y a su buen nombre, y el Estado debe respetarlos y hacerlos respetar (Constitución Política de 1991, artículo 15).<br/>";
let fundamentos_Libre_Desarrollo_Personalidad = "Todas las personas tienen derecho al libre desarrollo de su personalidad sin más limitaciones que las que imponen los derechos de los demás y el orden jurídico (Constitución Política de 1991, artículo 16).<br/>";
let fundamentos_Proteccion_Esclavitud_Servidumbre_TrataHumana = "En Colombia está prohibida la esclavitud, la servidumbre y la trata de seres humanos en todas sus formas (Constitución Política de 1991, artículo 17).<br/>";
let fundamentos_Libertad_Conciencia = "En Colombia se garantiza la libertad de conciencia. Nadie puede ser molestado por razón de sus convicciones o creencias ni compelido a revelarlas ni obligado a actuar contra su conciencia (Constitución Política de 1991, artículo 18).<br/>";
let fundamentos_Libertad_Cultos = "En Colombia se garantiza la libertad de cultos. Toda persona tiene derecho a profesar libremente su religión y a difundirla en forma individual o colectiva (Constitución Política de 1991, artículo 19).<br/>";
let fundamentos_Libertad_Expresion = "Se garantiza a toda persona la libertad de expresar y difundir su pensamiento y opiniones, la de informar y recibir información veraz e imparcial, y la de fundar medios masivos de comunicación (Constitución Política de 1991, artículo 20).<br/>";
let fundamentos_Vivienda_Digna = "Toda(o) colombiana(o) tiene derecho a una vivienda digna. Es deber del Estado fijar las condiciones necesarias para hacer efectivo este derecho y promover planes de vivienda de interés social, sistemas adecuados de financiación a largo plazo y formas asociativas de ejecución de estos programas de vivienda (Constitución Política de 1991, artículo 51).<br/>";